# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  id-token: write
  pages: write

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --dev
      - run: npx eslint .
      - run: npm test --passWithNoTests
        env:
          CI: true
          REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_KEY: ${{ secrets.REACT_APP_SUPABASE_KEY }}
          REACT_APP_URL: ${{ secrets.REACT_APP_URL }}
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.31.0-focal
    steps:
      - run: npm install
      - name: Wait for netlify
        uses: probablyup/wait-for-netlify-action@3.2.0
        id: netlify-done
        with:
          site_id: 7755e198-c65a-4dc9-8f0c-45fa53b54ee2
          max_timeout: 9999999
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Run Playwright tests
        run: npx playwright test
        env: 
          NETLIFY_URL: ${{ steps.netlify-done.outputs.url }}
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: playwright-report/
      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v1
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30


